title: johnny
author: johnny
description: currently doing a BSc Major in Physics combined with a D.Met (Diploma in Meteorology) and a Minor in Math. Interested in weather, computing, Vim.
avatar: "./assets/images/me.png"
url: "https://fadullo.ca"
baseurl: ""
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude:
  - archive

nav_pages:
  - index.markdown
  - writing.markdown
  - projects.markdown

social_links:
  - platform: github
    user_url: "https://github.com/fadullo"
  # - platform: tiktok
  #   user_url: "https://www.tiktok.com/@jsfadullo"
  # - platform: twitter
  #   user_url: "https://x.com/fadullotwt"
  - platform: instagram
    user_url: "https://instagram.com/jsfadullo"
  # - platform: spotify
  #   user_url: "https://open.spotify.com/user/4wrnu63xlunbdovbv9m6toq0o"

contact_links:
  - type: email
    label: "jsfadullo@dal.ca"
    url: "mailto:jsfadullo@dal.ca"
  # - type: email
  #   label: "jsfadullo@gmail.com"
  #   url: "mailto:jsfadullo@gmail.com"

  # - type: phone
  #   label: "+1 902 000 0000"
  #   url: "tel:+19020000000"

projects_links:
  # - label: "Profile"
  #   url: "https://www.roblox.com/users/926820216/profile"
  #   icon: "gamepad"
  - label: "DevForum"
    url: "https://devforum.roblox.com/u/johnnynaynay/summary"
    icon: "comments"

plugins:
  - jekyll-feed
